import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/layout/navbar";

const font42 = localFont({
  src: [
    {
      path: "../public/fonts/42dotSans-Light.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../public/fonts/42dotSans-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/42dotSans-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/42dotSans-Bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../public/fonts/42dotSans-ExtraBold.ttf",
      weight: "800",
      style: "normal",
    },
  ],
  variable: "--font-42dot",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${font42.variable} antialiased font-sans bg-white`}>
        <header>
          <nav>
            <Navbar />
          </nav>
        </header>
        {children}
        <footer></footer>
      </body>
    </html>
  );
}
